name: matrix

on:
  workflow_dispatch

jobs:
    python:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          python-version: ["3.9", "3.10", "3.11"]

      steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: setup python
        uses: action/setup-python@v5
        with:
           python-version: ${{ matrix.python-version }}

      - name: check python version
        run: python --version
